#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend sammykingx.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 530406-web-01 52.91.150.183:80
        server 530406-web-02 54.174.242.55:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
